### ISSUE TITLE
[BUG] ZiGi doesnt recognises if a PDS member was replaced by copy

### ISSUE THREAD

**Issue by zszabo14** [zigi/zigi#355]
**Describe the bug**
If you copy a PDS member into the repo PDS ZiGi doesn't recognises the member as modified.

**Release of zigi**
2.7

**To Reproduce**
1. go into a non ZiGi PDS
2. use C to copy a member 
3. target PDS is a ZiGI repo pds
4. check in ZiGi

**Expected behavior**
ZiGi should recognize this as change, when start ZiGi check against .zigi or add a re-sync command

**Comment by lbdyck** [comment]
Was the member that was copied the same contents as the one it replaced and with the same ISPF statistics?

ZIGI should, if the ISPF stats are different, copy the new/updated member from the PDS to OMVS where git will determine if the contents have changed. If the ISPF stats are identical then ZIGI will not do the copy.

Please let us know if the member being copied has different ispf stats and different contents from the member it is replacing.

**Comment by wizardofzos** [comment]
beat me to it Lionel :)

**Comment by lbdyck** [comment]
It wasn't my goal to beat you :)

**Comment by wizardofzos** [comment]
Replayed it

Current settings from zigi
<img width="556" alt="Screenshot 2020-05-08 at 13 16 26" src="https://user-images.githubusercontent.com/117615/81400760-22683800-912e-11ea-9e15-849bdf481c1f.png">

Copy a member over it, then fully restart zigi

<img width="557" alt="Screenshot 2020-05-08 at 13 18 30" src="https://user-images.githubusercontent.com/117615/81400906-6c511e00-912e-11ea-93f1-3fe1e80b2d68.png">

As you see the stats differ (and I know the contents do too..)

yet. no info that it's changed?
Also git status shows nothing...

**Comment by wizardofzos** [comment]
Also... seems not to detect when edit outside of zigi?

**Comment by lbdyck** [comment]
i've not been able to recreate with the dev-lbd branch so perhaps that was fixed.

**Comment by wizardofzos** [comment]
checking in our 2.8-rc now

**Comment by wizardofzos** [comment]
Hey zszabo14, can you confirm your repodir is outside of your homefolder?
Think Lionel and me just found and fixed it (locally)

**Comment by zszabo14** [comment]
![image](https://user-images.githubusercontent.com/42870072/81406191-6f054080-9139-11ea-8810-c26d4c1dd99e.png)

**Comment by zszabo14** [comment]
![image](https://user-images.githubusercontent.com/42870072/81406279-90662c80-9139-11ea-92ba-3f1a1f4bf313.png)
inside my home dir

**Comment by zszabo14** [comment]
![image](https://user-images.githubusercontent.com/42870072/81406831-9a3c5f80-913a-11ea-92f6-622fe00c835f.png)

btw: in ZiGi there should bi a FIND command like in ISPF
![image](https://user-images.githubusercontent.com/42870072/81406913-bf30d280-913a-11ea-85bf-7116ead652d7.png)

**Comment by wizardofzos** [comment]
would you be willing to also share the contents of ˜/.zigi (just an ls or udlist output will suffice)

**Comment by zszabo14** [comment]
(51@@)HH05849:/u/hh05849/git/WWFDO/.zigi(137):>ls -la    
total 64                                                 
drwxrwxrwx   2 HH05849  DEFLT1      8192 May  8 08:44 .  
drwxrwxrwx   6 HH05849  DEFLT1      8192 May  8 05:52 .. 
-rw-rw----   1 HH05849  DEFLT1      2904 May  8 08:44 JCL
-rw-rw-rw-   1 HH05849  DEFLT1       629 Mar 26 17:27 dsn

(51@@)HH05849:/u/hh05849/git/WWFDO/.zigi(136):>cat JCL          
W4AMROAC 19/08/05 20/05/08 01 10 08:42   119   123     0 HH05849
W4AMXLD1 20/03/26 20/03/26 01 00 17:23    18    16     0 HH05849
W4AMXLD2 20/03/26 20/03/26 01 00 17:23    17    15     0 HH05849
W4ANROAC 19/07/24 19/08/09 01 16 07:08   117    16     0 HUZ03DP
W4APXLD1 20/03/26 20/03/26 01 00 17:23    15    15     0 HH05849
W4ASSET  19/03/07 19/03/07 01 00 10:31    48    47     0 D212709
W4CETRG  19/06/01 20/03/30 01 71 10:31   107    35     0 HH05849
W4CNTRG  19/06/01 20/03/30 01 70 10:31   107    35     0 HH05849
W4CURXLD 19/03/07 19/03/07 01 00 11:54    41    39     0 D212709
W4CUSTSB 19/03/07 19/03/07 01 02 12:04   162   160     0 D212709
W4EMXLD1 20/03/26 20/03/26 01 00 17:23    15    15     0 HH05849
W4FLDW   19/03/07 19/03/07 01 04 12:24   322   315     0 D212709
W4FNAR10 19/03/07 19/03/07 01 00 12:26    16    16     0 D212709
W4FNAR20 19/03/07 19/03/07 01 01 16:24    16    16     0 D212709
W4FNAR30 19/03/07 20/03/30 01 01 10:35    16    16     0 HH05849
W4HKTRG  19/06/01 19/06/05 01 71 09:22   106    35     0 HU48654
W4HUTRG  19/06/01 20/04/01 01 73 10:28   107    35     0 HUZ03DS
W4IBMLER 19/03/07 19/03/07 01 01 16:39    30    30     0 D212709
W4INATRG 19/06/01 19/06/05 01 73 09:22   106    35     0 HU48654
W4IP01LD 19/03/07 19/03/07 01 00 16:43    15    15     0 D212709
W4KOTRG  19/06/01 19/06/05 01 68 09:22   106    35     0 HU48654
W4LDCONT 19/11/12 19/11/25 01 01 09:05    16    16     0 HU48654
W4LDLINV 19/09/20 19/09/20 01 00 12:30    16    16     0 HUZ03DP
W4LMSTRG 19/06/01 19/06/05 01 68 09:22   106    35     0 HU48654
W4L20XLD 19/03/07 19/03/07 01 00 16:44    39    39     0 D212709
W4MCTRG  19/06/01 19/06/05 01 67 09:22   106    35     0 HU48654
W4NILSLD 19/03/07 19/03/07 01 00 16:45    15    15     0 D212709
W4NZLTRG 19/06/01 19/06/05 01 72 09:22   106    35     0 HU48654
W4TEST   19/11/12 20/03/30 01 01 10:31    17    16     0 HUZ03DS
W4TWTRG  19/06/01 19/06/05 01 69 09:22   106    35     0 HU48654
W4USXLD1 19/03/07 19/03/07 01 00 16:50    16    16     0 D212709
W4USXLD2 19/03/07 19/03/07 01 00 16:57    15    15     0 D212709
W4WARINV 20/03/26 20/05/08 01 01 08:29    47    46     0 HH05849
W4YIP1LD 19/03/08 19/03/08 01 00 07:35    16    16     0 D212709
W4YIP2LD 19/03/08 19/03/08 01 00 07:51    16    16     0 D212709
W4YIP3LD 20/03/26 20/03/26 01 00 17:23    18    16     0 HH05849
W4YIP7LD 19/03/07 19/07/24 01 04 09:42    16    16     0 HH05849
W4101XLD 20/03/26 20/03/26 01 00 17:23    40    39     0 HH05849
W4109XLD 20/03/26 20/03/26 01 00 17:23    42    39     0 HH05849
W4110XLD 20/03/26 20/03/26 01 00 17:23    41    39     0 HH05849
W4121XLD 20/03/26 20/03/26 01 00 17:23    41    39     0 HH05849
W4381XLD 20/03/26 20/03/26 01 00 17:23    41    39     0 HH05849
W45G2XLD 19/03/08 19/03/08 01 00 02:48    40    39     0 D212709
X4YIP4LD 19/03/07 19/07/24 01 03 09:39    16    16     0 HH05849

**Comment by wizardofzos** [comment]
hmmmm not what I would expect :)

could you try and run the v2r8-rc branch? If you've trouble getting it from git I can package for you if you require?

**Comment by zszabo14** [comment]
not so easy to deploy anything here....is a production system

**Comment by wizardofzos** [comment]
zszabo, the v2r8 should fix this issue. I don't wanna hear about developing on a production system, but keep in mind that zigi will run prefectly fine from 'your own datasets'  too :)

just stick it in <TSOPREFIX>.<MAYBE>.<ANOTHER>.ZIGI.EXEC etc... and it will run just fine. ZIGI does all the LIBDEFs for the panels and such from where it runs...
