### ISSUE TITLE
Zigi deletes a non-Zigi copy of a dataset

### ISSUE THREAD

**Issue by andrew890** [zigi/zigi#376]
**Describe the bug**

If you switch from a branch that does not contain a particular dataset to a branch that does contain the dataset and the dataset already exists on z/OS, the existing dataset is deleted and replaced with the Zigi copy.

**Release of zigi**
v2R9

**To Reproduce**
1. Add a dataset to Zigi
2. Create a new branch
3. Delete the dataset in the branch
4. Recreate the dataset with new contents but do not add it to Zigi
5. Checkout the original branch containing the dataset

The dataset with new contents is deleted and replaced with the Zigi copy

**Expected behavior**
An error message and the existing dataset is left intact. The exact behavior should reflect Git's behavior as much as possible.

**Additional context**
Similar problems can happen with undetected modifications when doing a checkout.
Probably, before doing any Git operation that modifies the working copy, Zigi should check the zOS datasets for modifications and copy them to OMVS so Git will detect the errors.

That doesn't work for datasets that do not exist in the working copy, so Zigi should also query Git for new datasets created by the checkout and make sure they don't already exist.

**Comment by wizardofzos** [comment]
I think in this case your expected behaviour is the way it should work.  
This is sort of an 'edge-case', yet something I would not like to see happen :)

Think we gonna have to try and 'fix' this in the next release....

**Comment by lbdyck** [comment]
How should this be 'fixed'?

1) when zigi opens a repository it always checks for updates in the z/OS datasets and copies them to OMVS for git awareness
2) zigi attempts to mimic git as much as possible so when changing branches the z/OS datasets are updated to reflect the status of the new branch just as the omvs files are 'updated' by git to reflect the same state.

Please advise.

**Comment by andrew890** [comment]
The OMVS files are a proxy for the z/OS datasets, so before every git operation they should reflect the contents of the z/OS datasets.

Before any git operation, any changes in the z/OS datasets should be copied to the OMVS files. Then, if the git operation is successful the changes should be copied to the z/OS datasets. I think then in most cases git itself should protect you from making data destroying changes.

The question of how to handle existing datasets added in git and datasets deleted in git is where the problems arise.

My initial thoughts are:

If a new dataset is added in git, and it already exists on z/OS:

Option 1) Copy the existing contents to the git working copy, and let git flag the problem. However it's possible git will always give an error if the files already exist, so this processing might be redundant. I don't know enough about what git considers an error.
Option 2) After the git operation, copy the dataset contents from z/OS to the working copy so difference show up as changes in git. People can then undo the changes if required so z/OS datasets match what is in git. The problem with this is that processing is possibly counter-intuitive, i.e. you have to commit a change into git if you want no change to the z/OS datasets.
Option 3) Ask the user if they want to replace the z/OS dataset contents from the working copy, or update the working copy from the z/OS dataset.

Any of these options require querying the git operation for new datasets and checking whether they exist before running the git command.

If a dataset is deleted in git:

- Ask the user whether they want to keep or delete the dataset on z/OS after removing the connection from the working copy.

**Comment by lbdyck** [comment]
In testing the 3.01 dev branch I did the following:

1. created a repo and added 5 datasets to it
2. created a new branch and removed a dataset without deleting the z/OS copy of it
3. changed back to original branch and all 5 datasets are there as expected
4. changed to the new branch and only 4 datasets are displayed as expected
    - the removed dataset is not in the repo at this point BUT the z/OS dataset still exists
5. Then removed a member from a PDS while in the new branch
6. change to master branch and member has 'returned'
7. change to new branch and the member is gone - as expected

Is this what you expect to happen?

**Comment by wizardofzos** [comment]
I think the thing here is a mixture of what's in this thread...
Andrew said: "The OMVS files are a proxy for the z/OS datasets, so before every git operation they should reflect the contents of the z/OS datasets."

From a 'true git'perspective (and the way I initially envisioned ZIGI) it's the other way around. Mere semantics but with a little twist. 

GIT has no knowledge of z/OS datasets, only OMVS files and folders. So with that perspective, the z/OS datasets are a proxy for the OMVS files and folders.

I think the cleanest way would be (in Lionels scenario above) : 

1. create a repo add 5 datatsets, for arguments sake : USER.REPO.A to USER.REPO.E
2. add all, commit
3. Create a new branch (one-less)
4. Delete a dataset (USER.REPO.E) from the branch (should not even be possible IMHO to *not* remove the z/OS dataset as the OMVS part is 'the truth')
5. commit.
6. Now USS and z/OS are 'in sync'
7. checkout the master branch
8. USER.REPO.E reappears
9. checkout one-less branch
10. USER.REPO.E dissapears again

I know this is NOT the way it works now in ZIGI, as for one we allow deletion of stuff from the REPO without reflecting that in the z/OS mirror of the REPO...

How (and if) we're going to this solution is a totally different matter, and should required a lot of up-front thinking :)

**Comment by lbdyck** [comment]
NOTE: the z/OS dataset should never be deleted unless the user overtly does so. It may disappear from the repository display of datasets but it still exists as a z/OS dataset.

**Comment by lbdyck** [comment]
Try the v3r01-dev branch and see if it now works the way you would like it to. See the release notes for other updates. This is NOT a release candidate as yet - just a developing branch so far.

**Comment by andrew890** [comment]
> 1. created a repo and added 5 datasets to it
> 2. created a new branch and removed a dataset without deleting the z/OS copy of it
> 3. changed back to original branch and all 5 datasets are there as expected

What happened to the contents of the z/OS dataset from before you switched back to the original branch? In the test they were probably the same, but that is a special case - Zigi needs to assume they might be different. This is where the options 1-3 above come in.

> 4. changed to the new branch and only 4 datasets are displayed as expected
>    * the removed dataset is not in the repo at this point BUT the z/OS dataset still exists
> 5. Then removed a member from a PDS while in the new branch
> 6. change to master branch and member has 'returned'
> 7. change to new branch and the member is gone - as expected
> 
> Is this what you expect to happen?

I think so, apart from 3.

Deleting or not deleting a dataset is a difficult problem.

If you don't delete it you have the situation where old datasets are lying around with out of date content, and you have to manually manage them. It creates a problem when you switch back and forth between branches and the dataset exists in only one branch. It creates problems if you rename a dataset - you end up with datasets being resurrected and multiple datasets with the same or slightly different content when you switch between branches.

On the other hand, if you do delete datasets it creates a problem if you switch from a branch where the dataset is managed in Zigi to one where it is not managed. In pure git this would be a delete, which is fine, because everything is inside the working copy. In z/OS the datasets are loosely linked and can exist independent of the working copy. Perhaps Zigi needs to keep a permanent record of datasets that have been deleted/renamed so that it can distinguish between datasets that it should delete and datasets that are not being Zigi managed in a particular branch/commit.

This is a difficult issue. The link between git and z/OS datasets is very difficult to get right so it works well in all situations. It would be useful to get some input from other z/OS people who have more git experience than I do.

**Comment by andrew890** [comment]
> Andrew said: "The OMVS files are a proxy for the z/OS datasets, so before every git operation they should reflect the contents of the z/OS datasets."
> 
> From a 'true git'perspective (and the way I initially envisioned ZIGI) it's the other way around. Mere semantics but with a little twist.
> 
> GIT has no knowledge of z/OS datasets, only OMVS files and folders. So with that perspective, the z/OS datasets are a proxy for the OMVS files and folders.

If you imagine a world where git did understand z/OS datasets, the OMVS copies of the datasets would not exist. Zigi should try to emulate what you would see if the OMVS copies didn't exist and git was working directly with the z/OS datasets. This is the mental model most people will have anyway when they are using Zigi to manage z/OS datasets. The z/OS datasets are the real data, the OMVS copies are just an unfortunate implementation requirement. They are just a stepping stone between the z/OS dataset and a commit in the repository.

**Comment by lbdyck** [comment]
Please try the v3r01-dev  branch and see if it functions the way you would like, or what needs to be changed.

**Comment by lbdyck** [comment]
Haven't been able to recreate with the v3r01 or the newer v3r02 dev branches - please advise.

**Comment by andrew890** [comment]
What is the intended behavior?

If I switch from a branch that does not include a particular dataset to a branch that does, what is supposed to happen to the dataset and its contents? If I switch back and forth between the 2 branches, what is supposed to happen?

If I switch from branch A, which contains the dataset, to branch B which does not, to branch C which contains the dataset but the members are different from branch A, what is supposed to happen?

I don't know what to test because I don't know what Zigi should do in these scenarios.

**Comment by lbdyck** [comment]
If you switch from Branch A to Branch B and a dataset does not exist in B then the dataset is just no part of the repository but it is NOT deleted from z/OS.  Then switching from B to A it will become part of the repository again and since it already exists it will not be updated from the OMVS files unless something changed.

Changing between branches the members are treated differently.  If the member does not exist in the new branch it will generate a prompt to inform you that it will be deleted from the PDS and you will have the option to prevent the deletion or allow it.

hope this makes sense.
