### ISSUE TITLE
[BUG] Unable to add dataset/file to the git index with non-default encoding

### ISSUE THREAD

**Issue by cietpfm** [zigi/zigi#383]
**Describe the bug**
Unable to add dataset/file to the git index with non-default encoding

**Release of zigi**
v3r00

**To Reproduce**
1. Create repository
2. Specify IBM-500 as zos-workingtree-encoding
3. Add a dataset
4. Attemp to add untracked file(s)
5. Fatal error displayed "added file untagged, set correct file tag"

**Expected behavior**
File(s) successfully added to the index.

**Screenshots**
None.

**Additional context**
In general, the file system knows the contents of a file only as a set of bytes.
In z/OS UNIX, file tags are a way to identify the code set of the text data within files.
z/OS Git relies upon the file tagging feature of z/OS UNIX.
If a file is not tagged, it is generally presumed to be encoded in IBM-1047 (EBCDIC).

It is my understanding that Zigi does not explicitly tag text files, leaving the user subject to the underlying idiosyncrasies: 

    git init repo1047
    cd repo1047
    echo "*   git-encoding=iso8859-1 zos-working-tree-encoding=IBM-1047" > tmp
    iconv -f 1047 -t 819 tmp > .gitattributes
    chtag -tc 819 .gitattributes
    rm -rf tmp
    touch README
    git add README

    warning: README added file have been automatically tagged IBM-1047 because they were untagged yet the .gitattributes file specifies they should be tagged

    git init repo500
    cd repo500
    echo "*   git-encoding=iso8859-1 zos-working-tree-encoding=IBM-500" > tmp
    iconv -f 1047 -t 819 tmp > .gitattributes
    chtag -tc 819 .gitattributes
    rm -rf tmp
    touch README
    git add README

    fatal: README added file untagged, set correct file tag

As a solution, Zigi should explicitly tag files according to the chosen repository default.

**Comment by cietpfm** [comment]
Prototype to render Zigi compatible with non-default encodings

https://github.com/wizardofzos/zigi/compare/v3r03-experimental...cietpfm:bug-383

**Comment by cietpfm** [comment]
Prototype to make Zigi compatible with non-default encodings

https://github.com/wizardofzos/zigi/compare/v3r03-experimental...cietpfm:bug-383

**Comment by mfsysprog** [comment]
Please note that git 2.26.2 as recently release by Rocket software will significantly change the behaviour with respect to encodings:

From the release notes:
In addition to the platform-independent changes between Git release 2.14.5 and 2.26.2, the following changes apply to the z/OS port.Many more character encodings are now supported on z/OS
The Git encoding (the character encoding used in the Git server repositories) for text will now always be UTF-8
There are no longer 'default' encodings applied for files in the working tree. This means that, for any given file, if no treatment is specified in gitattributes file:
- Git will not set a file tag during clone/checkout
- Git will not allow a tagged file to be added to the index

**Comment by lbdyck** [comment]
This will be handled in ZIGI 3.10 (feel free to check out the fork at github.com/lbdyck/zigi/ where this is under development.  All files that have no encoding defined will be tagged with the default as defined in .gitattributes. 3.10 also has many other fixes and enhancements. It is getting closer but could use more exercising to make sure that it is solid before it is pulled back into the wizardofzos stream.
