### ISSUE TITLE
[BUG] Some z/OS dataset changes not detected

### ISSUE THREAD

**Issue by andrew890** [zigi/zigi#394]
**Describe the bug**
After z/OS datasets are updated, some changes are not detected by Zigi

**Release of zigi**
3.10

**To Reproduce**
1.  Checkout git@github.com:andrew890/tersedecompress-testdata.git, branch zigi (warning: it's large, about 1GB, sorry)
2.  Run Z.JCL/terse.txt to recreate the test data
3.  Select the repository again in Zigi. Zigi checks for changes, but not all the PACK & SPACK datasets are shown as updated
4.  Verify that datasets that show as unchanged have in fact been changed: There is a timestamp towards the end, search for 2021 and observe that the timestamp is the time that the data was recreated in step 2.

**Expected behavior**
All modified datasets are detected by Zigi.

**Comment by lbdyck** [comment]
cloned the repo - it isn't in zigi format.  Also unable to find a Z.JCL/terse.txt file.

**Comment by andrew890** [comment]
You need to checkout branch "zigi", not master

**Comment by lbdyck** [comment]
I see the problem but can't explain it. ZIGI is detecting that the z/OS dataset changed based upon the last reference date and is doing a cp of the /zOS file to the OMVS filesystem.  Then it is up to git to detect the file changes.

With these files:
hlq.Z.FB.GRAMMAR.LSP.PACK
hlq.Z.FB.GRAMMAR.LSP.SPACK

The PACK change is detected by git but the SPACK change is not.

This I can not explain but ZIGI is doing what it is supposed to.

At this point I'm at a loss to resolve this.

(note I'm working with git 2.14

**Comment by andrew890** [comment]
It appears that Zigi **does not** copy the datasets.
If I search for the timestamp in the omvs dataset, it is still the old time. The last update time on the omvs dataset is also unchanged.

Also, in 3.02 when I delete the repository the same datasets where the update was not detected are not deleted and left behind (when I tested that in 3.10 no datasets were deleted so it doesn't help with diagnostics).

It appears that there is a problem in the Zigi code that builds and processes a list of datasets - something that is shared between checking for updates and deleting the datasets.

**Comment by lbdyck** [comment]
I've tried your testcase and have found that all changed datasets are copied.  If you can provide a recreate able testcase and scenario I'm happy to work on it but at this time I can't recreate.

**Comment by andrew890** [comment]
In your Feb 7 update you said you could see the problem. I don't understand what you mean when you say you can't reproduce it.

I am very sure that the datasets are not copied by Zigi. I have confirmed by:
- browsing the datasets and looking at the timestamps in the data
- checking the last update date in OMVS
- verifying by type 14 and type 92 SMF records that Zigi did not read the dataset or write the omvs file.

I don't know what else I can do to prove it.

**Comment by lbdyck** [comment]
I will try a few other tests on a different LPAR 

Lionel B Dyck <sdg><
Sent from my iPad Pro 10.5
Website: www.lbdsoftware.com

"Worry more about your character than your reputation.  Character is what you are, reputation merely what others think you are." - John Wooden
