### ISSUE TITLE
[BUG] - Getting INVALID DATA SET NAME during commit

### ISSUE THREAD

**Issue by ehrocha** [zigi/zigi#396]
**Describe the bug**
Getting these messages after commit :
IKJ56709I INVALID DATA SET NAME, '.A089712.ASM.SOURCE'     
IKJ56709I INVALID DATA SET NAME, '.A089712.ASM.SOURCE'     

It looks like the commit still completes fine, but messages are issued.

**Release of zigi**
V3R02

**To Reproduce**
1. Create Repo.
2. Add a PDS to the repo.
3. Add all members (A besides the dataset name).
4. Commit.
5. Exit ZIGI.
6. Navigate to the dataset using 3.4 , ADD or DELETE a member .
7. Go back to ZIGI , it will show your dataset in [??] Untracked  status. 
8. Enter A besides the dataset to add/remove the member 
9. Commit.

**Expected behavior**
Commit without errors.

**Screenshots**
N/A

**Additional context**

**Comment by wizardofzos** [comment]
Does this happen in 3.11 too?
Can you send (redacted) screens of repo panels? (specifically interested in datasetnames and the 'qualignore' setting...
