### ISSUE TITLE
fatal: could not read Username EDC5137I Inappropriate I/O control operation.

### ISSUE THREAD

**Issue by steve3213** [zigi/zigi#403]
**Describe the bug**
While having a local repository on the mainframe via ZIGI, we have pushed all of our changes to the local repository. When we are trying to make a commit to the remote depository which is our GitHub Repository, we are getting the following error: "fatal: could not read Username for '<This is where it lists our github repository url address>': EDC5137I Inappropriate I/O control operation."
We do have different usernames for our github repository site (which is our MS ID) and our zigi application (Which is our TSO ID). We have linked the two sites with a SSH key which is defined in ZIGI and GitHub.
We do have a work around to use putty as a workaround but would like to work exclusively in ZIGI. We want to be able to use username/password in ZIGI if possible

**Release of zigi**
3.10

**To Reproduce**
1. Make changes in local repository
2. push/commit changes to local repository
3. push/commit changes to remote repository

**Expected behavior**
Make changes to the master catalog in remote repository with updates to data members that have been change.
To see what changes were committed and have some sort of version control of master code.

**Comment by wizardofzos** [comment]
Heya Steve,

Is your z/OS able to connect to github?
You can try this with ZIGI to just do a clone of ZIGI (user clone option then enter git@github.com:zigi/zigi.git as repo... (and the other fields of course)

You can also try (from USS) to do an `ssh git@github.com` and see what it does?

If your `~/.ssh/id_rsa.pub`  is present at yout GitHub account this should all work...

(maybe paste the output of `ssh -vvv git@github.com`  here (after any sanitizing of 'critical'  data)

**Comment by REXXdude** [comment]
Hi, Wizardofzos.

I work with Steve3213. We're trying to get ZIGI to work with remote repositories using SSH keys (not user ID and password, for which ZIGI doesn't have an interface). I've created public and private keys on the mainframe side, and added the public key in github.

I've tried ssh git@github.com. Nothing ever comes back from this, my session hangs waiting.

I'm left wondering if our z/OS actually can connect to github. Apart from this, which doesn't seem to work, what else can I try to find out?

**Comment by REXXdude** [comment]
I should mention this is after I issued these:
ssh-agent $SHELL
ssh-add
both of which were successful.

**Comment by wizardofzos** [comment]
Heya,

If you still there? Head on over to https://meet.mainframe.community/zigi :)

**Comment by REXXdude** [comment]
I'm there.

**Comment by wizardofzos** [comment]
Things to try:

Open a session to your big iron....(SSH or TSO/ISPF)

try to 'ping' github.com (

**Comment by wizardofzos** [comment]
> I'm there.

but ur on mute?

**Comment by wizardofzos** [comment]
What's the output on that ssh -vvv git@github.com?

**Comment by REXXdude** [comment]
Results:

CS V2R4: Pinging host GITHUB.COM (140.82.114.3)
Ping #1 response took 0.033 seconds.
***

**Comment by wizardofzos** [comment]
ok so connectivity is ok :)

**Comment by REXXdude** [comment]
No output at all. My session simply hangs and never comes back.

**Comment by REXXdude** [comment]
Perhaps I'm doing it wrong. What should I use for ***@***.******@***.*** ?

**Comment by wizardofzos** [comment]
ok.....so then what does ssh -V show?

**Comment by wizardofzos** [comment]
also pls retry that meet..... link,... might be more efficient :)
(i can open a skype too if that's more convenient for you?)

**Comment by REXXdude** [comment]
ssh -V output:
OpenSSH_7.6pl, LibreSSL 3.0.2.

**Comment by wizardofzos** [comment]
meet.google.com/rfp-yybe-ysy
?

**Comment by REXXdude** [comment]
My company blocks meet.google.com, apparently, though I was able to get onto it a little while ago.

**Comment by wizardofzos** [comment]
ah ok maybe that's why the meet.mainframe.... failed too...... any other options for you?

I've just skype as backup

**Comment by REXXdude** [comment]
This is my work machine, so what I'm able to connect to is governed by company standards.

**Comment by wizardofzos** [comment]
hmza ok....... well....... teleram/whatsapp on your private mobile device?

**Comment by REXXdude** [comment]
It doesn't have Skype either, alas.

**Comment by REXXdude** [comment]
One moment...

**Comment by wizardofzos** [comment]
send out an email to wizard@zdevops.com  . . . . we can share details there..... :)

**Comment by REXXdude** [comment]
I'll go to that meeting site on my private tablet.

**Comment by wizardofzos** [comment]
ok...
ill be there :)

**Comment by wizardofzos** [comment]
use chrome?

**Comment by wizardofzos** [comment]
as your on mute too :)

**Comment by REXXdude** [comment]
Using my tablet. All indications suggest I'm not on mute; gave permission to use the microphone.
I assume you can see me.

**Comment by wizardofzos** [comment]
nope ;( hangout google meet work on the tablet?
opening https://meet.google.com/abh-zjbr-bez

**Comment by REXXdude** [comment]
I'll try that. One moment...

**Comment by REXXdude** [comment]
Looks like Skype will work best.

**Comment by wizardofzos** [comment]
lols ;)
ok.....send me an email at wizard@zdevops.com and we'll plan a moment.... im just sliding into a call here ;)

**Comment by REXXdude** [comment]
Sent. Thanks. Ping me on Skype whenever you're free.

**Comment by wizardofzos** [comment]
Issue 'solved'... need to check zigi for how to handle the know_hosts... closing this for posterity.... creating new ticket for us to check the known_hosts processing :)
