### ISSUE TITLE
[BUG] ZIGIEDIT panel problem after installation of 3.11

### ISSUE THREAD

**Issue by WernerB1** [zigi/zigi#421]
**Describe the bug**
There is a problem with the panel ZIGIEDIT in the installation file of 3.11.
The panel consists of only one line (see **Screenshots**).
I think that CRLF are missing.

**Release of zigi**
3.11

**To Reproduce**
yes

**Expected behavior**

**Screenshots**
 BROWSE    **.V311.ZIGI.PANELS(ZIGIEDIT) - Line 0000000000 Col 001 080 
 Command ===>                                                  Scroll ===> CSR  
********************************* Top of Data **********************************
)PANEL KEYLIST(ISRSPEC,ISR)                                                     
******************************** Bottom of Data ********************************

 UDLIST    /u/ported/zigi/ZIGI.PANELS/ZIGIEDIT                                                                                      Line 0000000000 Col 001 160 
 Command ===>                                                                                                                                  Scroll ===> CSR  
************************************************************************* Top of Data **************************************************************************
)PANEL KEYLIST(ISRSPEC,ISR)                                                     /* Copied from IBM's ISREDDE2 Panel and modified with panel rexx */             
************************************************************************ Bottom of Data ************************************************************************

**Additional context**
To run ZIGI 3.11 we copied the panel from 3,10.

**Comment by lbdyck** [comment]
Which version of git are you using?

**Comment by WernerB1** [comment]
We are using
bash-4.3# git --version
git version 2.14.4_zos_b09

**Comment by lbdyck** [comment]
You should upgrade to git 2.26 and this issue will disappear.  At least I haven't seen it with 2.26.

hope this helps.

**Comment by WernerB1** [comment]
Hi Lionel, i don't understand. What does this have to do with git? I think this is a problem with the installation file. After unpacking, the zigiedit panel consists of only one line (missing line feed). All the other panels have the necessary line feeds.
greetings

**Comment by lbdyck** [comment]
the 'installation' file - where did you get the installation file?

Try this:

1. get into omvs and create a directory for zigi
2. enter: git clone git@github.com:zigi/zigi.git
3. then enter at the prompt: ./.zginstall.rex and follow the prompts to create the z/OS datasets

This is what I just did and the results were successful.

let me know.

**Comment by WernerB1** [comment]
the only difference was that we downloaded the file from https://anaconda.org/zdevops/zigi/files, then we transferd it to USS then unpack and the rest was the same. May be this file was corrupted.
We could not use the way from our host because it has no direct internet access.

**Comment by WernerB1** [comment]
if the panel ZIGIEDIT is the same as in 3.10 than all is OK and you could close the ticket and thx for support.

**Comment by lbdyck** [comment]
The panel is the same.  In the future, as we do plan updates to zigi, you should look at how you'll perform that update.

You can go to github.com/zigi, click on the Code drop down and then click on Download ZIP.  Then on your pc ftp, sftp, the zip file to your omvs home and unzip and then do the zginstall.rex.

**Comment by WernerB1** [comment]
this is how we will do it in the future
