### ISSUE TITLE
[BUG] same source changed from two users

### ISSUE THREAD

**Issue by WernerB1** [zigi/zigi#423]
**Describe the bug**
User1 changed source1 - save it (F3) - issue addall - then commit - and then push

I checked it via GitLab - OK

User2 also changed source1 - save it (F3) - issue addall - then commit - and then push

The following is displayed:
  ZIGI e                       ZIGI Git Messages                                                                           
 Command ===>                                                                                                             
************************************************************************* Top of Data ************************************
----------------------------------------------------------------------                                                    
Command: cd /u/insewb1/repos/si-start && git push -v                                                                      
Pushing to git@gitlab-master.develop.beta.ads:playground/si-start.git                                                     
time="2021-12-01T11:11:44+01:00" level=info msg="SSL_CERT_DIR is configured" ssl_cert_dir=/opt/gitlab/embedded/ssl/certs/ 
To gitlab-master.develop.beta.ads:playground/si-start.git                                                                 
 ! [rejected]        master -> master (non-fast-forward)                                                                  
error: failed to push some refs to 'git@gitlab-master.develop.beta.ads:playground/si-start.git'                           
hint: Updates were rejected because the tip of your current branch is behind                                              
hint: its remote counterpart. Integrate the remote changes (e.g.                                                          
hint: 'git pull ...') before pushing again.                                                                               
hint: See the 'Note about fast-forwards' in 'git push --help' for details.                                                
************************************************************************ Bottom of Data **********************************
action from user2:
F3
pull

The following is displayed:
 ZIGI e                       ZIGI Git Messages                                                                            
 Command ===>                                                                                                              
************************************************************************* Top of Data *************************************
Auto-merging ALMSSRC/LMSACVV                                                                                               
Auto-merging .zigi/ALMSSRC                                                                                                 
CONFLICT (content): Merge conflict in .zigi/ALMSSRC                                                                        
Automatic merge failed; fix conflicts and then commit the result.                                                          
----------------------------------------------------------------------                                                     
Command: cd /u/insewb1/repos/si-start && git pull -v                                                                       
time="2021-12-01T11:19:35+01:00" level=info msg="SSL_CERT_DIR is configured" ssl_cert_dir=/opt/gitlab/embedded/ssl/certs/  
From gitlab-master.develop.beta.ads:playground/si-start                                                                    
 = [up to date]      master                  -> origin/master                                                              
 = [up to date]      bw-flow-1               -> origin/bw-flow-1                                                           
 = [up to date]      bwroll1                 -> origin/bwroll1                                                             
 = [up to date]      develop                 -> origin/develop                                                             
 = [up to date]      eufr-master-patch-69240 -> origin/eufr-master-patch-69240                                             
 = [up to date]      insesl1branch1          -> origin/insesl1branch1                                                      
 = [up to date]      slbranch                -> origin/slbranch                                                            
************************************************************************ Bottom of Data ***********************************

after that user2 would like to see the diffs and issues the D line command in front of the source and ZIGI displays the short message 'No Diff'
see panel:
  Menu   Help                                                                  
────────────────────────────────────────────────────────────────────────────── 
ZIGI ember List ----------------- (ZIGI v3r11) ----------------------- No Diff     <== it shows 'No Diff' ... Why?
Command ===>                                                                Scroll ===> CSR  
Current Dataset   : 'INSEWB1.LMSE.ALMSSRC'                                F3   
Current Repository: /u/insewb1/repos/si-start                                  
Current Branch    : master                                                     
                                                                               
S    Member      Status                         Type  Size    Mod-Date  Mod-Time  Userid    
      CEEUOPT                                        T      111   15/11/09           00:00  LMS6100   
D   LMSACVV   [M ] Ready to commit   T      137   21/12/01           11:10  USER2   
      LMSAC00                                       T      875   21/11/10           12:14  USER3   

could you explain me why no differences are recognized?

**Release of zigi**
3.11

**To Reproduce**
yes, like in description

**Comment by lbdyck** [comment]
Did user2 do a pull after the user1 update to get the current source level? Are they working in the same branch (not a good idea)?

Ideally both should be working in different branches and then merge when ready.
