### ISSUE TITLE
Stucking in "git clone"

### ISSUE THREAD

**Issue by markons** [zigi/zigi#441]
**Describe the bug**
"**git clone**..." for the repository does not exist from OMVS

**Release of zigi**
Which release of zigi are you reporting this bug against?
latest

**To Reproduce**
see below...

**Expected behavior**
I've executed the installing instructions up to 
3. Create an account at github.com and add your SSH public key to it.
...and then...
4. From OMVS-shell invoke: git clone git@github.com/wizardofzos/zigi.git
...which produced the error message
"fatal: repository 'git@github.com/wizardofzos/zigi.git' does not exist "

**Screenshots**

**Additional context**
**I can clone the repository very well from my local Github desktop using the given URL.**

**Comment by wizardofzos** [comment]
Looks like some outdated docs ? COuld you tell me where you'd found those instructions?
ZIGI has moved to 'https://github.com/zigi/zigi'  a while back

**Comment by markons** [comment]
https://github.com/zigi/zigi/blob/master/ZIGI.README

"
3. Create an account at github.com and add your SSH public key to it.
4. From OMVS-shell invoke: git clone git@github.com/wizardofzos/zigi.git
"

...but then it was apparently the wrong link - sorry

**Comment by markons** [comment]
One other question to the same thread: all the panels have been downloaded without any problem. The only exception was the member "ZIGIEDIT" which is stored in a kind of binary format: https://github.com/zigi/zigi/blob/master/ZIGI.PANELS/ZIGIEDIT
How can one download this one in an appropriate, interpretable version?

**Comment by lbdyck** [comment]
You will have to use cp (or the Co:Z putpds) with the binary option to copy from the omvs repository to the z/OS PDS for the ZIGIEDIT panel.  It is stored in binary due to some ISPF panel attribute characters that would otherwise be corrupted with the EBCDIC to ASCII and ASCII to EBCDIC conversions.

**Comment by markons** [comment]
Thank you very much Lionel! cp with "-B" was the solution for me.
May I ask you another - a kind of "off-topic" - which is still somehow related by conversion problematic?
I have an open issue in Github here:
[](https://github.com/cschneid-the-elder/mapa/issues/104)
The short description: I can normally create a fat-jar file on my PC, and upload this as binary on OMVS.
It functions always well; the only issue up to now is the problem above. I can do what I will, the "antlr" parser part
of that jar does not convert well. 
Perhaps have you some idea with your overall experience...
Best regards
Gábor

**Comment by lbdyck** [comment]
I have updated the zginstall.rex so going forward, after the 3.14 release, this won't be an issue.  On the other issue I'm sorry but I can't help (don't use jar files).

**Comment by markons** [comment]
Hello Lionel,

thank you very much!

Regards
Gabor Markon
