### ISSUE TITLE
[BUG]Incorrect message at starting ZIGI

### ISSUE THREAD

**Issue by markons** [zigi/zigi#444]
**Describe the bug**
At starting ZIGI by "TSO ZIGI", an incorrect (error/warning) message will be shown. 

**Release of zigi**
Actual

**To Reproduce**
see screenshots below
1. 
2. 
3. 
4. 

**Expected behavior**
In the message referenced dataset/member exists, but will be shown as non-existent.
**Screenshots**
![image](https://user-images.githubusercontent.com/2115566/164196812-0e034006-b54d-41b3-9aac-09d300248b11.png)
![image](https://user-images.githubusercontent.com/2115566/164196859-1a07d03b-1fad-4085-a4bd-82e9fc2a22cb.png)
 

**Additional context**

**Comment by lbdyck** [comment]
This has been corrected with the 3.14 release which we are working on.

yes - it was a very annoying bug.
