### ISSUE TITLE
[BUG] x0D characters at the end of lines after cloning on USS

### ISSUE THREAD

**Issue by FALLAI-Denis** [zigi/zigi#449]
**Describe the bug**

Launching ./zginstall.rex fails:

```
>./zginstall.rex
      1 +++ /* REXX - must start in column 1 */?
IRX0013I Error running ./zginstall.rex, line 1: Invalid character in program
```

Presence of x0D characters at the end of lines for all files after cloning on USS.

**Release of zigi**

Last from github: v3r13

**To Reproduce**
1. download zigi from github in zip format on Windows Workstation
2. create a new repository on our Git Server: Bitbucket
3. initialize git repository on Windows Workstation:
> git init
> git add --all
> git commit -m "Initial Commit"
> git remote add origin ssh://git@xxxxx/\<project\>/\<repo.git\>
4. push repository on Bitbucket
> git push -u origin HEAD:master
5. clone repository on USS from Bitbucket (can't access to Github from USS)

Git config on Windows Workstation:
`core.autocrlf=true`

Git config on USS:
`core.autocrlf=true`

No extra eol on Bitbucket...

**Expected behavior**

Correct end of lines on USS

**Screenshots**

![image](https://user-images.githubusercontent.com/63861965/167423564-307048a8-27ec-477b-95b1-16a2d456f845.png)

![image](https://user-images.githubusercontent.com/63861965/167423449-d55eede5-934f-462d-8171-ef870ac5c87b.png)

![image](https://user-images.githubusercontent.com/63861965/167422537-b994baba-022b-402f-a45b-d19d7fec2edd.png)

**Comment by lbdyck** [comment]
Perhaps try downloading the zip file and then upload to z/OS OMVS and unzip there. I will try to come up with a way to recreate your issue.

![image](https://user-images.githubusercontent.com/42328411/167434224-4a0b71b3-3cd5-4eb5-a0fd-f192c6faa4d9.png)

**Comment by wizardofzos** [comment]
I want to add that installing it in the way you described is not something I had envisioned...
nonetheless, that method of bringing it in 'should' be working....,can you share your git version (on the mainframe) and the intermediate git version used on windows?

alternatively getting the XMIT file from CBTTAPE might be a better alternative?

**Comment by FALLAI-Denis** [comment]
Git version on Windows (Git bash):
```
$ git --version
git version 2.31.1.windows.1
```

Git version on USS (RocketSoftware):
```
>git --version  
git version 2.26.2-84               

```
I will eventually find where the problem comes from :-)

I cannot clone Github directly, whether on my Windows workstation or on USS: firewall problem...
I have to go through the download in zip format.

I redid the manipulation from the beginning. It's the "git add --all" command that reports line ending problems.

![image](https://user-images.githubusercontent.com/63861965/167442995-ccd75b05-d3ff-469f-9564-c0f12f4223a7.png)

**Comment by wizardofzos** [comment]
those versions are current enough one would say... again... as stated....not a use case I had envisioned :)

hope the CBT XMIT (or upcoming new conda installer) will work for you?

If you've conda you can download the files and install via the --offline option (by uploading them to the USS?)

**Comment by wizardofzos** [comment]
Link to conda installer: https://anaconda.org/zdevops/zigi (older zigi version tbh)

**Comment by FALLAI-Denis** [comment]
I can't use conda or miniconda...

Only files encoded in IBM-1047 are impacted, and they are explicitly encoded in IBM-1047:

![image](https://user-images.githubusercontent.com/63861965/167455466-f950e8a0-8547-4fab-88a2-9c055a06d339.png)

Files encoded ASCII (859) do not have extra x'0D'...  (no encoding conversion during clone).

This leads me to suspect that there is a problem with Git for z/OS converting the encoding...

**Comment by FALLAI-Denis** [comment]
Solved! (but not understood...)

I added "eol=lf" for all files in .gitattributes..., push on Bitbucket... clone on USS: no more x'0D' on IBM-1047 encoded files...         

![image](https://user-images.githubusercontent.com/63861965/167460113-6650c9d9-d4bc-4e1f-bb6d-95d7dc803be2.png)

**Comment by FALLAI-Denis** [comment]
I progress...
A problem in the installation script due I think to the presence of a "$" character in the HLQ... (sorry, our standards are like that...).

```
Copying 189 of 189       Member: ZIGIVCNV as Text                                                                                   
cp: FSUM6258 cannot open file "//'T.BASEPRPO.OUTDEV.ZIGI.ZGSTAT.EXEC' ": EDC5061I An error occurred when attempting to define a file
 to the system.                                                                                                                     
                                                                                                                                    
Completed - z/OS datasets created:                                                                                                  
                                                                                                                                    
'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZIGI.GPLLIC'                                                                                         
'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZIGI.README'                                                                                         
'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZIGI.RELEASE'                                                                                        
'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZIGI.EXEC'                                                                                           
'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZIGI.PANELS'                                                                                         
                                                                                                                                    
Note that using this installation path does not allow the ISPF                                                                      
statistics to be recreated. Other than the missing ISPF statistics                                                                  
everything has been successfully installed on z/OS.                                                                                 
                                                                                                                                    
To recreate the ISPF statistics execute the following command                                                                       
after returning to TSO/ISPF:                                                                                                        
                                                                                                                                    
TSO EX 'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZGSTAT.EXEC' EX                                                                               
                                                                                                                                    
After it completes successfully it can be deleted.                                
```

**Comment by FALLAI-Denis** [comment]
try to complete installation:

1. manually create file for ZGSTAT.EXEC (LRECL=80?)
2. manually copy lrhg.rexx in it
3. run it


```
     48 *-* repodir ='/u/J070188/DepotsGIT/zigi-master'                         
        >L>   "/u/J070188/DepotsGIT/zigi-master"                                
     49 *-* hlq ='T$BASEPR.BASEPRPO.OUTDEV'                                     
        >L>   "T$BASEPR.BASEPRPO.OUTDEV"                                        
     51 *-* Address ISPExec                                                     
     52 *-* load_info = loadispf()                                              
    306 +++  'LMMSTATS DATAID('status') Member('member') user('sysvar(sysuid)') 
     "LMMFind DATAID("status") Member("member") STAT                            
 S(YES)"                end                                                     
                /* ------------------------------ *                             
                                     * Add each member info to a stem *         
                             * ---------------------                            
 --------- */                                     c = mem.0 + 1                 
                                          if sysrecf                            
 m /=                                                                           
     52 +++ load_info = loadispf()                                              
 IRX0030I Error running exec, line 306: Name or string > 250 characters         
```

**Comment by lbdyck** [comment]
Somethings awry as that statement (306) should end with a '

thus: ` 'LMMSTATS DATAID('status') Member('member') user('sysvar(sysuid)')' `

and from your message that does not appear to be the case.  The ending ' is in column 73 if that helps - did you perhaps do a renum on the zginstall.rex code or on the zgstat.exec dataset?

**Comment by FALLAI-Denis** [comment]
What's expected?
Setup is made by /etc/profile, running a `export_vars.sh` 

![image](https://user-images.githubusercontent.com/63861965/167467111-48a34fe8-87fb-402d-9ce1-886eac51a63e.png)

**Comment by FALLAI-Denis** [comment]
> Somethings awry as that statement (306) should end with a '
> 
> thus: `'LMMSTATS DATAID('status') Member('member') user('sysvar(sysuid)')'`
> 
> and from your message that does not appear to be the case. The ending ' is in column 73 if that helps - did you perhaps do a renum on the zginstall.rex code or on the zgstat.exec dataset?

uh... autonum in effect...

![image](https://user-images.githubusercontent.com/63861965/167467531-b58e7ddc-136b-4168-b904-fb334de30cc6.png)

**Comment by FALLAI-Denis** [comment]
> I progress...
> 
> A problem in the installation script due I think to the presence of a "$" character in the HLQ... (sorry, our standards are like that...).
> 
> 
> 
> ```
> 
> Copying 189 of 189       Member: ZIGIVCNV as Text                                                                                   
> 
> cp: FSUM6258 cannot open file "//'T.BASEPRPO.OUTDEV.ZIGI.ZGSTAT.EXEC' ": EDC5061I An error occurred when attempting to define a file
> 
>  to the system.                                                                                                                     
> 
>                                                                                                                                     
> 
> Completed - z/OS datasets created:                                                                                                  
> 
>                                                                                                                                     
> 
> 'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZIGI.GPLLIC'                                                                                         
> 
> 'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZIGI.README'                                                                                         
> 
> 'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZIGI.RELEASE'                                                                                        
> 
> 'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZIGI.EXEC'                                                                                           
> 
> 'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZIGI.PANELS'                                                                                         
> 
>                                                                                                                                     
> 
> Note that using this installation path does not allow the ISPF                                                                      
> 
> statistics to be recreated. Other than the missing ISPF statistics                                                                  
> 
> everything has been successfully installed on z/OS.                                                                                 
> 
>                                                                                                                                     
> 
> To recreate the ISPF statistics execute the following command                                                                       
> 
> after returning to TSO/ISPF:                                                                                                        
> 
>                                                                                                                                     
> 
> TSO EX 'T$BASEPR.BASEPRPO.OUTDEV.ZIGI.ZGSTAT.EXEC' EX                                                                               
> 
>                                                                                                                                     
> 
> After it completes successfully it can be deleted.                                
> 
> ```                                                  
> 
> 
> 
> I think this relate to this code:
> 
> ```
> 
> 000395     zgstat_dsn = "'"ckothlq".ZGSTAT.EXEC'"       
> 
> 000396     cmd = 'cp -v  lrhg.rex "//'zgstat_dsn '"'    
> 
> 000397     cmd = cmd '&& rm lrhg.rex'                   
> 
> 000398     x = bpxwunix(cmd,,so.,se.,env.)              
> 
> 000399     if so.0 > 0 then                             
> 
> 000400     do i = 1 to so.0;say so.i;end                
> 
> 000401     if se.0 > 0 then                             
> 
> 000402     do i = 1 to se.0;say se.i;end        
> 
> ```                                                                                      

Note that all files have a forced .ZIGI. intermediate level qualifier but not for &HLQ..ZGSTAT.EXEC file.

**Comment by FALLAI-Denis** [comment]
"Zigi needs to find the git executable in the 'PATH'. To determine the 'PATH' zigi sources /etc/proiile and ~.profile. Make sure one of these files contains the correct EXPORT statements."

For us "RocketSoftware Open AppDev for Z", ROAD4Z, is installed from a SMP/E distribution (support licenced products).
/etc/profile does'nt include explicit export for Git and others informations, it use a call to a setup shell script:
. /path-to-script/setup-script.sh 

This setup shell script is a loop for scan of a folder containing one shell script for each product in ROAD4Z. 
Each individual shell script do exports for himself.

**Comment by wizardofzos** [comment]
if you're "in" USS and 'git' works you can use https://gist.github.com/wizardofzos/0b7fb5d5ec00bbec1e3b6c0dab8027cf to create an env file tailored for your setup... wanna give that a try?

**Comment by FALLAI-Denis** [comment]
Hi @wizardofzos 

I create a gitenv.sh with script `create_gitenv.sh`

![image](https://user-images.githubusercontent.com/63861965/167854375-59901a9e-2d9c-4673-bfe6-9647eaf9bbc1.png)

But I'm still stuck on this step

![image](https://user-images.githubusercontent.com/63861965/167855813-5e92ad3b-64b4-4ccc-b10b-045d9439a627.png)

![image](https://user-images.githubusercontent.com/63861965/167857039-e6693340-7202-4f87-bdaf-5a346cb98a53.png)

Missing "EXPORT"?

![image](https://user-images.githubusercontent.com/63861965/167861174-1425c723-9b8c-4877-a83c-30c35c256d83.png)

No...

![image](https://user-images.githubusercontent.com/63861965/167861390-628ac649-e8c0-4127-8072-9af6ea982a92.png)

I think there is a compatibility issue between Zigi and the new RocketSoftware Open AppDev for z/OS distribution mode.

Detail of the implementation of ROAD4Z configuration variables:

![image](https://user-images.githubusercontent.com/63861965/167862425-5447bf8d-6192-4624-bb8c-d4c8ea002d45.png)

![image](https://user-images.githubusercontent.com/63861965/167862550-fdafe667-031a-4654-8d60-d97d52a267fd.png)

![image](https://user-images.githubusercontent.com/63861965/167862658-dbb3d958-d76f-484d-8049-38fa0ec5a24a.png)

![image](https://user-images.githubusercontent.com/63861965/167862727-2fcd3c64-72e1-4891-af4a-4702d0594da0.png)

I think that Zigi should plan to manage the configuration variables it needs on its own and not depend on an external context (ROAD4Z) that it does not control.
This could be done through a panel for entering the necessary configuration variables.

**Comment by FALLAI-Denis** [comment]
What is precisely expected in environnement settings for zigi?
I will manually create the setven script.

**Comment by wizardofzos** [comment]
Make sure git works on your interactive shell. Then run this https://gist.github.com/wizardofzos/0b7fb5d5ec00bbec1e3b6c0dab8027cf

**Comment by FALLAI-Denis** [comment]
Hi @wizardofzos 

that’s what i do (i think i do) as detailed above… 
« gitenv » created from OMVS session with Git operational. 
Something i do’nt understand or something wrong… 
Shell is bash as recommanded by RocketSoftware.

**Comment by FALLAI-Denis** [comment]
Hi,

Regarding the initial problem, namely the presence of x'0D' characters at the end of the line of the converted files, I solved my problem.

Being used to working on Windows, I added the auto.crlf=true option in my Git configuration on z/OS-USS...
This is what added the x'0D' characters to all converted files (different encoding for Git internal storage and for the working directory on z/OS).

I wonder if auto.crlf=input should be declared in the system configuration of Git for z/OS to avoid any problems in the future...

**Comment by FALLAI-Denis** [comment]
Configuration error in /u/<user>/.gitconfig: presence of `auto.crlf=true` which a priori should only be used in a Windows context and not on a Unix system.
