### ISSUE TITLE
Sourcing an environment for git 

### ISSUE THREAD

**Issue by gngrossi** [zigi/zigi#468]
I noticed the comment in the ZIGI exec.
 
/* quircky thing, we need to export HOME as we are
not running a login shell via bpxwunix */         
 
I have worked with a colleague who is testing a batch REXX exec that is using git. One thing we did was to call bpxwunix with a login shell (/bin/sh). It seems to be working for us. I didn’t realize that non-interactive sessions could use a login shell until I needed to run CoZ batch and use git. After reading this, it became clear.
https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html

Also, I prefer providing a sourcing profile to ZIGI and be able to change it when I need to. The parameters /ENV and /ENVR are a nice enhancement, On USS, my .profile doesn't need to source the same env-file ZIGI is using.

thanks

**Comment by lbdyck** [comment]
Since zigi is intended for ispf usage primarily the /ENV and /ENVR seem fine to me.  For batch you can source an git/zigi specific environment file in your batch use.  I'm open to suggestions for zgbatch which is our sample batch application.

**Comment by lbdyck** [comment]
The update you requested for changing the environment variable file from within the application has been put into the 318dev branch on my fork and a pull request has been generated. There is a new command on the primary menu of GITEnv.

**Comment by gngrossi** [comment]
closing
