### ISSUE TITLE
Updating the config after F3 cancel?

### ISSUE THREAD

**Issue by gngrossi** [zigi/zigi#477]
ZIGI v3r18

From the Local Repositories panel, after typing the "config" command, proceeding to the Set Defaults panel and using F3 to cancel  results in an "Updated" message when returning to the Local Repositories panel.

![image](https://github.com/zigi/zigi/assets/115715798/b88889cd-5602-433a-a6c3-b8cf514d0a10)

**Comment by lbdyck** [comment]
Got it and will fix with 3.19 - oversight in not testing the return code from the panel - thanks for catching.

**Comment by gngrossi** [comment]
Fixed...closing
