### ISSUE TITLE
[BUG] Differences in stats file because LMMLIST and Co:Z getpds return different values for vers/mod and time

### ISSUE THREAD

**Issue by catherdersoftware** [zigi/zigi#493]
**Describe the bug**
The stats file may have unneeded updates because ISPF `LMMLIST` and Co:Z `getpds` return different values for vers/mod (`LMMLIST` uses leading zeroes, `getpds` uses spaces) and time may not always include seconds.

**Release of zigi**
3.19 (but all since Dovetail support was added in  3.11)

**To Reproduce**
1. Update with Co:Z available, commit, push
2. Update without Co:Z, diff of stats file shows differences due to zero/spaces

**Expected behavior**
Consistent behavior no matter the source of the vers/mod. 

**Additional context**
Because `LMMLIST` is always available, `getpds` values should be adjusted to match. However, if `ZLTIME` does not include seconds and `ZLSECS` is available, it should be added to the time (`LMMSTATS` accepts it).

**Comment by catherdersoftware** [comment]
Please assign this to me, it will be added to my USER8 support.

**Comment by lbdyck** [comment]
instead of updating the `getpds` stats after the fact requiring post processing - why not ask Kurt to fix - or adjust the `LMMSTATS` to match the `getpds` format to keep it simple.

**Comment by catherdersoftware** [comment]
`LMMSTATS` is guaranteed to be available. `getpds` is not. `getpds` output is very UNIX®-like without the leading zero, and it fits USS (it's fine for a pipe). Also, there are likely many scripts built around the non-leading-zero output for `getpds`, and we shouldn't ask for a breaking change.

We can provide a fix more easily now than wait for Dovetail to make a change to their behavior. We could ask for an option but I think that's unnecessary.

**Comment by lbdyck** [comment]
I would  agree - change the `zigi` `lmmstats` process to match `getpds` :)

**Comment by catherdersoftware** [comment]
> I would agree - change the `zigi` `lmmlist` process to match `getpds` :) (corrected)

That makes us forcing a change to `LMMLIST` to conform to a third-party utility instead of the other way. That bothers me.

**Comment by lbdyck** [comment]
it bothers me as well but it is the quickest way to solve it and not require users to upgrade if/when Co:Z makes a change.

**Comment by catherdersoftware** [comment]
I think we need a poll of users to see how many use Co:Z.

**Comment by lbdyck** [comment]
I posted a request in the Co:Z community forum for the leading zeros to be supplied when requesting ispf stats.

**Comment by lbdyck** [comment]
Fixed in zigi
